# Created by Jennifer Souvannasing
print('_' * 45)
text = input('What does the CAT say? ')
textlength = len(text)
print('_' * 45)
print(' ')
print('            {}'.format('-' * textlength))
print('          < {} >'.format(text))
print('            {}'.format('-' * textlength))
print('         /')
print('        /')
print('       /')
print(' /\-/\ ')
print(' (0.o) ')
print('  >^<  ')
